### PR TITLE
Recognissimo vosk stt

### PR DESCRIPTION
**Pull request by frissonlabs**

### CODE REVIEW

**Comment by Elringus** [comment]
@frissonlabs please restore the branch so I can reset the commits (you've leaked naninovel sources to the public).

**Comment by frissonlabs** [comment]
@Elringus I just restored the branch. I'm really sorry about that, it was purely an accident.

**Comment by Elringus** [comment]
Ah, nevermind, it won't let hard reset with a restored branch. Nothing we can do now, I guess.

**Comment by frissonlabs** [comment]
Can you possibly submit a request to delete this pull request?

https://support.github.com/contact?flow=pr_removal&subject=Delete%20Pull%20Request&tags=rr-remove-data

**Pull request closed without merging**
